from enum import Enum

class ClaimCategory(str, Enum):
    CONSULTATION = "CONSULTATION"
    DIAGNOSTIC = "DIAGNOSTIC"
    PHARMACY = "PHARMACY"
    DENTAL = "DENTAL"
    VISION = "VISION"
    ALTERNATIVE_MEDICINE = "ALTERNATIVE_MEDICINE"

class DocumentType(str, Enum):
    PRESCRIPTION = "PRESCRIPTION"
    HOSPITAL_BILL = "HOSPITAL_BILL"
    LAB_REPORT = "LAB_REPORT"
    PHARMACY_BILL = "PHARMACY_BILL"
    DIAGNOSTIC_REPORT = "DIAGNOSTIC_REPORT"
    DENTAL_REPORT = "DENTAL_REPORT"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    UNKNOWN = "UNKNOWN"

class DocumentQuality(str, Enum):
    GOOD = "GOOD"
    LOW = "LOW"
    UNREADABLE = "UNREADABLE"

class DecisionVerdict(str, Enum):
    APPROVED = "APPROVED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class TraceStepStatus(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    DEGRADED = "DEGRADED"
    SKIPPED = "SKIPPED"

class RuleSource(str, Enum):
    DETERMINISTIC = "DETERMINISTIC"
    LLM = "LLM"

class RejectionReason(str, Enum):
    WAITING_PERIOD = "WAITING_PERIOD"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    POLICY_INACTIVE = "POLICY_INACTIVE"
    MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND"
    BELOW_MINIMUM = "BELOW_MINIMUM"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    CATEGORY_NOT_COVERED = "CATEGORY_NOT_COVERED"

class DocumentIssueType(str, Enum):
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    WRONG_DOCUMENT = "WRONG_DOCUMENT"
    UNREADABLE = "UNREADABLE"
    PATIENT_MISMATCH = "PATIENT_MISMATCH"
